# Generated by Django 4.1.7 on 2023-04-11 04:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_listing_current_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="price",
            new_name="value",
        ),
    ]
