# Generated by Django 4.1.7 on 2023-04-18 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_comment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchers",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
