# Generated by Django 4.1.7 on 2023-04-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_listing_watchers"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="brand",
            field=models.CharField(
                blank=True,
                choices=[("AP", "Apple"), ("SM", "Samsung"), ("NK", "Nokia")],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[("N", "New"), ("U", "Used"), ("B", "Broken")],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LUX", "Luxury"),
                    ("LTS", "Latest Model"),
                    ("STD", "Standard Model"),
                    ("LEG", "Legacy"),
                ],
                max_length=3,
            ),
        ),
    ]
