# Generated by Django 4.1.7 on 2023-04-20 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_listing_brand_listing_condition_listing_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="value",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="current_price",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_price",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999999999),
                ]
            ),
        ),
    ]
