# Generated by Django 4.1.7 on 2023-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_alter_bid_value_alter_listing_current_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LUX", "Luxury"),
                    ("LTS", "Latest Model"),
                    ("OLD", "Older Model"),
                    ("LEG", "Legacy"),
                ],
                max_length=3,
            ),
        ),
    ]
